image: Visual Studio 2015

version: 1.4.0

branches:
  only:
    - master
    - release

max_jobs: 4

environment:
  boto:
    secure: E6k49x/FqxNauxAKPasdtiWLRC+wsr+BDXhm7qf+FMNjhUYa7sSkbdsml+UDesn24d+02ZFr2QvLiaC0ISH1vsokTaZbnD9I0dcF7vijA2AJrqQ2NZ/JvJdWY43ABZINrZt7eaQHAuVJmZ1zwqCldJaUALCPu1FCcfKlPQWNJqlI4aTJ9CqQEZ6Iava52ArolQEUIbY97WPZX/yqp5Np1ok5hDC8Vhfbj34VusBzGeDvgDvYmqjg+hklEEUa8zrSICoQDJHpLA59P1MiIpaCkGEW8d8MtbRYytwjE3cFbKSHnCB1V6YacztbsDzFedE3hFRBJeAMeOkD8a3MwcwrgQ==
  OKJVERSION: 1.4.0
  matrix:
  - TARGET_ARCH: x64
    QT: C:\Qt\5.10.1\msvc2015_64
    PLATFORM: amd64
    COMPILER: msvc
    VSVER: 14
    LONGARCH: x86_64
    BITS: 64bit
  - TARGET_ARCH: x86
    QT: C:\Qt\5.10.1\msvc2015
    PLATFORM: x86
    COMPILER: msvc
    VSVER: 14
    LONGARCH: x86
    BITS: 32bit

clone_depth: 1

init:
  - set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%

clone_folder: c:\projects\openkj

install:
  - ps: |
      Write-Host "Installing gsutil for gcloud storage deployment"
      $zipPath = "$($env:APPVEYOR_BUILD_FOLDER)\gsutil.zip"
      (New-Object Net.WebClient).DownloadFile('https://pub.storage.googleapis.com/gsutil.zip', $zipPath)
      7z x $zipPath -y
      $bytes = [System.Convert]::FromBase64String($env:boto)
      [System.IO.File]::WriteAllBytes("$env:USERPROFILE\.boto", $bytes) 
  - ps: |
      Write-Host "Installing GStreamer..." -ForegroundColor Cyan
      Write-Host "Platform - $($env:LONGARCH)"
      $msiPath = "$($env:USERPROFILE)\gstreamer.msi"
      $gstInstallUrl = "https://storage.googleapis.com/okj-installer-deps/gstreamer-1.0-$($env:LONGARCH)-1.12.4.msi"
      $gstDevelInstallUrl = "https://storage.googleapis.com/okj-installer-deps/gstreamer-1.0-devel-$($env:LONGARCH)-1.12.4.msi"
      Write-Host "Downloading..."
      (New-Object Net.WebClient).DownloadFile($gstInstallUrl, $msiPath)
      Write-Host "Installing..."
      cmd /c start /wait msiexec /package $msiPath /passive ADDLOCAL=ALL
      Write-Host "Installed" -ForegroundColor Green
  - ps: |
      Write-Host "Installing GStreamer dev..." -ForegroundColor Cyan
      $msiPath = "$($env:USERPROFILE)\gstreamer-devel.msi"
      Write-Host "Downloading..."
      (New-Object Net.WebClient).DownloadFile($gstDevelInstallUrl, $msiPath)
      Write-Host "Installing..."
      cmd /c start /wait msiexec /package $msiPath /passive ADDLOCAL=ALL
      Write-Host "Installed" -ForegroundColor Green
  - ps: |
      Write-Host "Downloading OpenSSL dll's"
      (New-Object Net.WebClient).DownloadFile("https://openkj.org/downloads/ssl-$($env:LONGARCH).zip", "c:\projects\openkj\ssl.zip")
      Write-Host "Done."
  - ps: |
      Write-Host "Downloading info-zip binary"
      (New-Object Net.WebClient).DownloadFile("https://storage.googleapis.com/okj-installer-deps/unzip.exe", "c:\projects\openkj\unzip.exe")
      Write-Host "Done."


build_script:
  - call "appveyor/build_windows.cmd"

artifacts:
  - path: OpenKJ-$(OKJVERSION)-$(BITS)-setup.exe
    name: installer

deploy_script:
# Upload all zip files from artifacts. 
# You upload by simple using local paths, but it is better to do this with $artifacts as you are in 100% sync with artifacts
# Or is simple do `- gsutil\gsutil cp <local_file_path> gs://my-test-bucket (thus avoiding NativeCommandError in build log)
  - ps: $artifacts.values | ForEach-Object {.\gsutil\gsutil cp $_.path gs://openkj-windows-builds-$($env:APPVEYOR_REPO_BRANCH)}
